FROM rocker/shiny

RUN install2.r learnr \
               remotes

RUN R -e 'remotes::install_github("rundel/learnrhash")'
RUN R -e 'remotes::install_github("wrightrc/interactiveBSE")'

COPY inst/tutorials /srv/shiny-server/

CMD ["/usr/bin/shiny-server.sh"]
